# Generated by Django 5.2.3 on 2025-06-20 10:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('authorid', models.AutoField(db_column='authorid', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstname', max_length=100)),
                ('lastname', models.CharField(db_column='lastname', max_length=100)),
                ('middlename', models.CharField(blank=True, db_column='middlename', max_length=100, null=True)),
                ('country', models.CharField(blank=True, db_column='country', max_length=100, null=True)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'author',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('deliverymethodid', models.AutoField(db_column='deliverymethodid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(db_column='description')),
                ('address', models.TextField(db_column='address')),
            ],
            options={
                'db_table': 'deliverymethod',
            },
        ),
        migrations.CreateModel(
            name='Format',
            fields=[
                ('formatid', models.AutoField(db_column='formatid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'format',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('genreid', models.AutoField(db_column='genreid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('orderstatusid', models.AutoField(db_column='orderstatusid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'orderstatus',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('publisherid', models.AutoField(db_column='publisherid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=255)),
                ('country', models.CharField(blank=True, db_column='country', max_length=100, null=True)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('roleid', models.AutoField(db_column='roleid', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='name', max_length=100)),
            ],
            options={
                'db_table': 'role',
            },
        ),
        migrations.RemoveField(
            model_name='book',
            name='id',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='stock_quantity',
        ),
        migrations.AddField(
            model_name='book',
            name='agerestriction',
            field=models.CharField(blank=True, db_column='agerestriction', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='authorid',
            field=models.IntegerField(blank=True, db_column='authorid', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='bookid',
            field=models.AutoField(db_column='bookid', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(db_column='language', default='Русский', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='pagecount',
            field=models.IntegerField(blank=True, db_column='pagecount', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='publicationdate',
            field=models.DateField(db_column='publicationdate', default='2020-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='publisherid',
            field=models.IntegerField(blank=True, db_column='publisherid', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='stockquantity',
            field=models.IntegerField(db_column='stockquantity', default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, db_column='description', null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(db_column='price', decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(db_column='title', max_length=255),
        ),
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('useraccountid', models.AutoField(db_column='useraccountid', primary_key=True, serialize=False)),
                ('firstname', models.CharField(db_column='firstname', max_length=100)),
                ('lastname', models.CharField(db_column='lastname', max_length=100)),
                ('middlename', models.CharField(blank=True, db_column='middlename', max_length=100, null=True)),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True)),
                ('password', models.CharField(db_column='password', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, db_column='last_login', default=django.utils.timezone.now, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(db_column='roleid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.role')),
            ],
            options={
                'db_table': 'useraccount',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cartid', models.AutoField(db_column='cartid', primary_key=True, serialize=False)),
                ('user', models.OneToOneField(db_column='useraccountid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cartitemid', models.AutoField(db_column='cartitemid', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity', default=1)),
                ('book', models.ForeignKey(db_column='bookid', on_delete=django.db.models.deletion.CASCADE, to='hello.book')),
                ('cart', models.ForeignKey(db_column='cartid', on_delete=django.db.models.deletion.CASCADE, to='hello.cart')),
            ],
            options={
                'db_table': 'cartitem',
            },
        ),
        migrations.CreateModel(
            name='BookGenres',
            fields=[
                ('bookgenresid', models.AutoField(db_column='bookgenresid', primary_key=True, serialize=False)),
                ('book', models.ForeignKey(db_column='bookid', on_delete=django.db.models.deletion.CASCADE, to='hello.book')),
                ('genre', models.ForeignKey(db_column='genreid', on_delete=django.db.models.deletion.CASCADE, to='hello.genre')),
            ],
            options={
                'db_table': 'bookgenres',
            },
        ),
        migrations.CreateModel(
            name='OrderTable',
            fields=[
                ('orderid', models.AutoField(db_column='orderid', primary_key=True, serialize=False)),
                ('totalamount', models.DecimalField(db_column='totalamount', decimal_places=2, max_digits=10)),
                ('orderdate', models.DateField(db_column='orderdate')),
                ('deliverymethod', models.ForeignKey(db_column='deliverymethodid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.deliverymethod')),
                ('orderstatus', models.ForeignKey(db_column='orderstatusid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hello.orderstatus')),
                ('user', models.ForeignKey(db_column='useraccountid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ordertable',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('orderitemid', models.AutoField(db_column='orderitemid', primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(db_column='quantity')),
                ('book', models.ForeignKey(db_column='bookid', on_delete=django.db.models.deletion.CASCADE, to='hello.book')),
                ('order', models.ForeignKey(db_column='orderid', on_delete=django.db.models.deletion.CASCADE, to='hello.ordertable')),
            ],
            options={
                'db_table': 'orderitem',
            },
        ),
    ]
